server:
  port: 8002
spring:
  application:
    name: MEIJIA-PLAT
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///cms?useSSL=false
    username: root
    password: admin