server:
  port: 9527
spring:
  application:
    name: MEIJIA-ZUUL
zuul:
  ignored-services: "*" #用*来通配符，忽略从9527端口通过服务名来调用
  prefix: "/services" #这是所有路径的前缀
  routes:
    plat:
      path: /plat/**
      service-id: meijia-plat
    product:
      path: /product/**
      service-id: meijia-product
hystrix:
  command:
    myusers-service:
      execution:
       isolation:
          thread:
            timeoutInMilliseconds: 5000
meijia-product: 
  ribbon:
    ConnectTimeout: 2000
    ReadTimeout: 8000