server:
  port: 8002
spring:
  application:
    name: MEIJIA-PLAT
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///meijia?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: admin