server:
  port: 9001
spring:
  application:
    name: MEIJIA-PRODUCT
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///meijia-product?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: admin
mybatis-plus:
  type-aliases-package: cn.itsource.meijia.domain,cn.itsource.meijia.query